---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels: 
    app.kubernetes.io/instance: aud2b-sep27-1
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: aud2b-sep27-1 
  name: aud2b-sep27-1
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 100Gi